-- Healthcare Patient Management System - schema (generated by scripts/export_ddl.py; do not edit by hand)
-- Build on an empty database:  mysql -u hc_app -p healthcare_db < db/schema.sql
-- admission_date / discharge_date are SIMULATED (the source dataset has no dates).
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE app_users (
	user_id INTEGER NOT NULL AUTO_INCREMENT, 
	username VARCHAR(50) NOT NULL, 
	password_hash VARCHAR(100) NOT NULL, 
	`role` ENUM('administrator','clinical_ops','analyst') NOT NULL, 
	is_active BOOL NOT NULL DEFAULT '1', 
	last_login_at DATETIME, 
	created_at DATETIME NOT NULL DEFAULT (now()), 
	CONSTRAINT pk_app_users PRIMARY KEY (user_id), 
	CONSTRAINT uq_app_users_username UNIQUE (username)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE medications (
	medication_id INTEGER NOT NULL AUTO_INCREMENT, 
	drug_name VARCHAR(40) NOT NULL, 
	CONSTRAINT pk_medications PRIMARY KEY (medication_id), 
	CONSTRAINT uq_medications_drug_name UNIQUE (drug_name)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE patients (
	patient_nbr BIGINT NOT NULL, 
	race VARCHAR(30), 
	gender VARCHAR(20), 
	is_deleted BOOL NOT NULL DEFAULT '0', 
	deleted_at DATETIME, 
	created_at DATETIME NOT NULL DEFAULT (now()), 
	updated_at DATETIME NOT NULL DEFAULT (now()), 
	CONSTRAINT pk_patients PRIMARY KEY (patient_nbr)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE pipeline_runs (
	run_id INTEGER NOT NULL AUTO_INCREMENT, 
	source_file VARCHAR(255) NOT NULL, 
	file_hash CHAR(64), 
	status ENUM('RUNNING','SUCCESS','FAILED','SKIPPED_DUPLICATE_FILE') NOT NULL, 
	started_at DATETIME NOT NULL DEFAULT (now()), 
	finished_at DATETIME, 
	rows_read INTEGER NOT NULL DEFAULT '0', 
	rows_loaded INTEGER NOT NULL DEFAULT '0', 
	rows_rejected INTEGER NOT NULL DEFAULT '0', 
	rows_skipped_existing INTEGER NOT NULL DEFAULT '0', 
	dq_summary_json JSON, 
	error_message TEXT, 
	triggered_by VARCHAR(50) NOT NULL, 
	CONSTRAINT pk_pipeline_runs PRIMARY KEY (run_id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE ref_admission_source (
	id INTEGER NOT NULL, 
	description VARCHAR(150) NOT NULL, 
	CONSTRAINT pk_ref_admission_source PRIMARY KEY (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE ref_admission_type (
	id INTEGER NOT NULL, 
	description VARCHAR(100) NOT NULL, 
	CONSTRAINT pk_ref_admission_type PRIMARY KEY (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE ref_discharge_disposition (
	id INTEGER NOT NULL, 
	description VARCHAR(255) NOT NULL, 
	is_expired_or_hospice BOOL NOT NULL DEFAULT '0', 
	CONSTRAINT pk_ref_discharge_disposition PRIMARY KEY (id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE ref_medical_specialty (
	specialty_id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(80) NOT NULL, 
	CONSTRAINT pk_ref_medical_specialty PRIMARY KEY (specialty_id), 
	CONSTRAINT uq_ref_medical_specialty_name UNIQUE (name)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE ref_payer (
	payer_id INTEGER NOT NULL AUTO_INCREMENT, 
	payer_code VARCHAR(10) NOT NULL, 
	CONSTRAINT pk_ref_payer PRIMARY KEY (payer_id), 
	CONSTRAINT uq_ref_payer_payer_code UNIQUE (payer_code)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE report_runs (
	report_id INTEGER NOT NULL AUTO_INCREMENT, 
	report_type VARCHAR(50) NOT NULL, 
	file_path VARCHAR(255) NOT NULL, 
	row_count INTEGER NOT NULL, 
	filters_json JSON, 
	generated_at DATETIME NOT NULL DEFAULT (now()), 
	triggered_by VARCHAR(50) NOT NULL, 
	CONSTRAINT pk_report_runs PRIMARY KEY (report_id)
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE audit_logs (
	id BIGINT NOT NULL AUTO_INCREMENT, 
	created_at DATETIME NOT NULL DEFAULT (now()), 
	user_id INTEGER, 
	username VARCHAR(50) NOT NULL, 
	`role` ENUM('administrator','clinical_ops','analyst') NOT NULL, 
	action ENUM('CREATE','UPDATE','DELETE','EXPORT') NOT NULL, 
	entity_type VARCHAR(30) NOT NULL, 
	entity_id VARCHAR(40) NOT NULL, 
	before_json JSON, 
	after_json JSON, 
	request_id VARCHAR(40), 
	ip_address VARCHAR(45), 
	CONSTRAINT pk_audit_logs PRIMARY KEY (id), 
	CONSTRAINT fk_audit_logs_user_id FOREIGN KEY(user_id) REFERENCES app_users (user_id) ON DELETE SET NULL
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at);

CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_type, entity_id);

CREATE TABLE dq_issues (
	issue_id BIGINT NOT NULL AUTO_INCREMENT, 
	run_id INTEGER NOT NULL, 
	encounter_id BIGINT, 
	rule_name VARCHAR(20) NOT NULL, 
	severity ENUM('error','warning','info') NOT NULL, 
	column_name VARCHAR(50), 
	bad_value VARCHAR(255), 
	action ENUM('rejected','corrected','flagged','metric') NOT NULL, 
	CONSTRAINT pk_dq_issues PRIMARY KEY (issue_id), 
	CONSTRAINT fk_dq_issues_run_id FOREIGN KEY(run_id) REFERENCES pipeline_runs (run_id) ON DELETE CASCADE
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE encounters (
	encounter_id BIGINT NOT NULL, 
	patient_nbr BIGINT NOT NULL, 
	admission_date DATE NOT NULL, 
	discharge_date DATE NOT NULL, 
	age_group VARCHAR(10) NOT NULL, 
	age_order TINYINT UNSIGNED NOT NULL, 
	admission_type_id INTEGER NOT NULL, 
	discharge_disposition_id INTEGER NOT NULL, 
	admission_source_id INTEGER NOT NULL, 
	specialty_id INTEGER, 
	payer_id INTEGER, 
	time_in_hospital TINYINT UNSIGNED NOT NULL, 
	num_lab_procedures SMALLINT NOT NULL, 
	num_procedures TINYINT UNSIGNED NOT NULL, 
	num_medications SMALLINT NOT NULL, 
	number_outpatient SMALLINT NOT NULL, 
	number_emergency SMALLINT NOT NULL, 
	number_inpatient SMALLINT NOT NULL, 
	number_diagnoses TINYINT UNSIGNED NOT NULL, 
	max_glu_serum ENUM('None','Norm','>200','>300') NOT NULL, 
	a1c_result ENUM('None','Norm','>7','>8') NOT NULL, 
	med_changed BOOL NOT NULL, 
	diabetes_med BOOL NOT NULL, 
	source_batch_id VARCHAR(100), 
	is_deleted BOOL NOT NULL DEFAULT '0', 
	deleted_at DATETIME, 
	created_at DATETIME NOT NULL DEFAULT (now()), 
	updated_at DATETIME NOT NULL DEFAULT (now()), 
	CONSTRAINT pk_encounters PRIMARY KEY (encounter_id), 
	CONSTRAINT fk_encounters_patient_nbr FOREIGN KEY(patient_nbr) REFERENCES patients (patient_nbr) ON DELETE RESTRICT, 
	CONSTRAINT fk_encounters_admission_type_id FOREIGN KEY(admission_type_id) REFERENCES ref_admission_type (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_encounters_discharge_disposition_id FOREIGN KEY(discharge_disposition_id) REFERENCES ref_discharge_disposition (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_encounters_admission_source_id FOREIGN KEY(admission_source_id) REFERENCES ref_admission_source (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_encounters_specialty_id FOREIGN KEY(specialty_id) REFERENCES ref_medical_specialty (specialty_id) ON DELETE RESTRICT, 
	CONSTRAINT fk_encounters_payer_id FOREIGN KEY(payer_id) REFERENCES ref_payer (payer_id) ON DELETE RESTRICT
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX ix_encounters_is_deleted_admission_date ON encounters (is_deleted, admission_date);

CREATE TABLE encounter_diagnoses (
	encounter_id BIGINT NOT NULL, 
	position TINYINT UNSIGNED NOT NULL, 
	icd9_code VARCHAR(10) NOT NULL, 
	CONSTRAINT pk_encounter_diagnoses PRIMARY KEY (encounter_id, position), 
	CONSTRAINT fk_encounter_diagnoses_encounter_id FOREIGN KEY(encounter_id) REFERENCES encounters (encounter_id) ON DELETE CASCADE
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE INDEX ix_encounter_diagnoses_icd9_code ON encounter_diagnoses (icd9_code);

CREATE TABLE encounter_medications (
	encounter_id BIGINT NOT NULL, 
	medication_id INTEGER NOT NULL, 
	dosage_status ENUM('Steady','Up','Down') NOT NULL, 
	CONSTRAINT pk_encounter_medications PRIMARY KEY (encounter_id, medication_id), 
	CONSTRAINT fk_encounter_medications_encounter_id FOREIGN KEY(encounter_id) REFERENCES encounters (encounter_id) ON DELETE CASCADE, 
	CONSTRAINT fk_encounter_medications_medication_id FOREIGN KEY(medication_id) REFERENCES medications (medication_id) ON DELETE RESTRICT
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE encounter_outcomes (
	encounter_id BIGINT NOT NULL, 
	readmitted ENUM('NO','>30','<30') NOT NULL, 
	readmitted_30d BOOL NOT NULL, 
	any_readmission BOOL NOT NULL, 
	is_readmission_eligible BOOL NOT NULL, 
	CONSTRAINT pk_encounter_outcomes PRIMARY KEY (encounter_id), 
	CONSTRAINT fk_encounter_outcomes_encounter_id FOREIGN KEY(encounter_id) REFERENCES encounters (encounter_id) ON DELETE CASCADE
)ENGINE=InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;

-- Views (db/queries/views.sql)
-- Reusable views. v_active_encounters is the SINGLE filter point: soft-deleted encounters (and encounters of
-- soft-deleted patients) can never reach a KPI, API list or export because every query reads from it.
-- race and gender are deliberately NOT exposed here (they live only on patients).

-- Business question: which encounters are live, with their outcome and human-readable categories?
CREATE OR REPLACE VIEW v_active_encounters AS
SELECT
    e.encounter_id, e.patient_nbr, e.admission_date, e.discharge_date,
    e.age_group, e.age_order,
    e.admission_type_id, t.description AS admission_type,
    e.admission_source_id, s.description AS admission_source,
    e.discharge_disposition_id, d.description AS discharge_disposition, d.is_expired_or_hospice,
    sp.name AS medical_specialty, py.payer_code,
    e.time_in_hospital, e.num_lab_procedures, e.num_procedures, e.num_medications,
    e.number_outpatient, e.number_emergency, e.number_inpatient, e.number_diagnoses,
    e.max_glu_serum, e.a1c_result, e.med_changed, e.diabetes_med, e.source_batch_id,
    o.readmitted, o.readmitted_30d, o.any_readmission, o.is_readmission_eligible
FROM encounters e
JOIN encounter_outcomes o ON o.encounter_id = e.encounter_id
JOIN ref_admission_type t ON t.id = e.admission_type_id
JOIN ref_admission_source s ON s.id = e.admission_source_id
JOIN ref_discharge_disposition d ON d.id = e.discharge_disposition_id
LEFT JOIN ref_medical_specialty sp ON sp.specialty_id = e.specialty_id
LEFT JOIN ref_payer py ON py.payer_id = e.payer_id
WHERE e.is_deleted = 0
  -- anti-join instead of JOIN patients: the optimizer scans encounters first (see docs/performance_notes.md)
  AND NOT EXISTS (SELECT 1 FROM patients p WHERE p.patient_nbr = e.patient_nbr AND p.is_deleted = 1);

-- Business question: which encounters can count in the denominator of a readmission rate?
-- (expired and hospice discharges could not be readmitted, so they are excluded.)
CREATE OR REPLACE VIEW v_readmission_base AS
SELECT * FROM v_active_encounters WHERE is_readmission_eligible = 1;

