"""Write the CREATE TABLE statements for every model to db/schema.sql (MySQL dialect).

Run from the repository root:  python scripts/export_ddl.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from sqlalchemy.dialects import mysql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from app.models import Base  # noqa: E402
from utils.logging_config import setup_logging  # noqa: E402

HEADER = """-- Healthcare Patient Management System - schema (generated by scripts/export_ddl.py; do not edit by hand)
-- Build on an empty database:  mysql -u hc_app -p healthcare_db < db/schema.sql
-- admission_date / discharge_date are SIMULATED (the source dataset has no dates).
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

"""


def build_ddl() -> str:
    """Return the DDL for all tables in dependency order."""
    dialect = mysql.dialect()
    parts = [HEADER]
    for table in Base.metadata.sorted_tables:
        parts.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n\n")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):  # CreateTable does not emit secondary indexes
            parts.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";\n\n")
    parts.append("SET FOREIGN_KEY_CHECKS = 1;\n\n-- Views (db/queries/views.sql)\n")
    parts.append((ROOT / "db" / "queries" / "views.sql").read_text(encoding="utf-8-sig"))
    return "".join(parts)


if __name__ == "__main__":
    log = setup_logging("export_ddl", log_dir=ROOT / "logs")
    out = ROOT / "db" / "schema.sql"
    out.write_text(build_ddl(), encoding="utf-8")
    log.info("Wrote %s (%d tables)", out, len(Base.metadata.sorted_tables))
